require('./compornents/header.tag')
require('./compornents/footer.tag')
<niltea-page>
	<niltea-header></niltea-header>
	<niltea-content></niltea-content>
	<niltea-footer></niltea-footer>
	<script>
	</script>
</niltea-page>